### ISSUE TITLE
Error in building VA 2020 two-region disaggregated model

### ISSUE THREAD

**Issue by bl-young** [USEPA/stateior#26]
```
Error in buildTwoRegionUseModel(state, year, ioschema = 2012, iolevel = iolevel,  : 
  RoUS (of Virginia)'s commodity output summed from two-region (total) Use table doesn't equal to RoUS's commodity output.
Calls: source ... eval -> assembleTwoRegionIO -> buildTwoRegionUseModel
Execution halted
````

https://github.com/USEPA/stateior/actions/runs/4549476400/jobs/8021585025

**Comment by jvendries** [comment]
As mentioned in the stop message, this error occurs because there is a difference in the values calculated for the commodity output for the RoUS calculated using the [US commodity totals](https://github.com/USEPA/stateior/blob/disagg/R/BuildModel.R#L563) and the RoUS calculated using the the [two table structure](https://github.com/USEPA/stateior/blob/disagg/R/BuildModel.R#L567) (RoUS2RoUS + RoUS2SoI) for the non-domestic tables. 

The specific sector in question is the Other commodity (last commodity in the table), where the value for the latter calculation is $2 million lower than the former. This is usually not a big enough value to create a > 1% difference threshold used as a check, but the value of the Other commodity is low enough in the first place that it results in a approximately a 1.1% difference. This is the only sector that fails this check for the 2020 disaggregated VA model. 

Since this is only happening in the 2020 disaggregated version, I am still tracking where exactly in the disaggregation steps the difference is introduced to the Other sector, as this is not a sector that is treated any differently for this year than any other in the current [test runs](https://github.com/USEPA/stateior/actions/runs/4549476400/jobs/8021585025). 

I'll post an update when I find the exact cause, but given the small difference I am inclined to suspect the error arises in the 2020 table due to a rounding error with smaller initial values in the VA tables for this particular year rather than an error with the disaggregation code per se.

**Comment by bl-young** [comment]
this issue is resolved following https://github.com/USEPA/stateior/commit/e1ed152e5630a6afb0e9d6a2659296870de6a2c6
